In [1]:
# 1. Read the CSV File and Display the First Few Rows:
# Load the data from 'Caterer_info.csv' into the DataFrame df2 and display the first few rows to understand the dataset's structure.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv(r'C:\Users\ASHOK\Downloads\Caterer_info.csv')
print("First few rows of the DataFrame:")
df.head()

First few rows of the DataFrame:


Unnamed: 0  Plate Cost  Decoration Price  Rating Caterer Name
0           0         280              5000     2.4            a
1           1         420              4300     3.8            b
2           2         390              5900     3.1            c
3           3         420              6900     4.6            d
4           4         280              6500     2.3            e

In [2]:
# 2. Check Data Types and Missing Values:
# Identify the data types of each column and check for any missing values in the dataset.
print("Data types and missing values:")
df.info()

Data types and missing values:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Unnamed: 0        20 non-null     int64  
 1   Plate Cost        20 non-null     int64  
 2   Decoration Price  20 non-null     int64  
 3   Rating            20 non-null     float64
 4   Caterer Name      20 non-null     object 
dtypes: float64(1), int64(3), object(1)
memory usage: 932.0+ bytes


In [3]:
# 3. Get Summary Statistics for Numeric Columns:
# Compute and Display summary statistics (mean, standard deviation, minimum, maximum, etc.) for the numeric columns in the DataFrame
print("Summary statistics for numeric columns:")
df.describe()

Summary statistics for numeric columns:


Unnamed: 0  Plate Cost  Decoration Price     Rating
count    20.00000   20.000000         20.000000  20.000000
mean      9.50000  374.000000       5430.000000   3.475000
std       5.91608   74.861275        918.866579   0.741176
min       0.00000  250.000000       4200.000000   2.300000
25%       4.75000  317.500000       4775.000000   3.100000
50%       9.50000  375.000000       5200.000000   3.550000
75%      14.25000  420.000000       6050.000000   4.000000
max      19.00000  500.000000       7000.000000   4.800000

In [4]:
# 4. Count Unique Values in Each Column:
# Understand the cardinality of unique values in each column.
print("Number of unique values in each column:")
df.nunique()

Number of unique values in each column:


Unnamed: 0          20
Plate Cost          14
Decoration Price    13
Rating              12
Caterer Name        20
dtype: int64

In [5]:
# 5. Check Unique Values in Each Column:
# Check for missing values in each column of the DataFrame and display the count of missing values.
for i in df.columns:
  print(f"\nCheck unique values in {i} column:")
  print(df[i].unique())


Check unique values in Unnamed: 0 column:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

Check unique values in Plate Cost column:
[280 420 390 360 250 370 400 380 440 490 320 480 500 310]

Check unique values in Decoration Price column:
[5000 4300 5900 6900 6500 7000 4200 4800 5800 5600 4700 4900 5400]

Check unique values in Rating column:
[2.4 3.8 3.1 4.6 2.3 3.3 3.4 4.  4.3 3.2 4.8 3.7]

Check unique values in Caterer Name column:
['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k' 'l' 'm' 'n' 'o' 'p' 'q' 'r'
 's' 't']


In [6]:
print("Missing values count in each column:")
print(df.isnull().sum())
print()
print('Missing values percentage in each column with:')
print(df.isnull().sum() *100/df.shape[0])

Missing values count in each column:
Unnamed: 0          0
Plate Cost          0
Decoration Price    0
Rating              0
Caterer Name        0
dtype: int64

Missing values percentage in each column with:
Unnamed: 0          0.0
Plate Cost          0.0
Decoration Price    0.0
Rating              0.0
Caterer Name        0.0
dtype: float64


In [7]:
# 6. Check for Missing Values:
# Check for duplicate rows in the DataFrame and display the count of duplicated values.
print("Duplicate values count in the Dataframe:")
df.duplicated().sum()

Duplicate values count in the Dataframe:


0

In [8]:
# Decorator Analysis: Identify the decorator with the highest rating. Identify the most cost-effective decorator based on decoration price.
# 1. Decorator Analysis:
# We start by identifying the decorator with the highest rating and the most cost-effective decorator based on decoration price.
# “highest_rated_decorator” stores the decorator with the highest rating, and “cost_effective_decorator” stores the decorator with the lowest decoration price.
highest_rated_decorator = df[df['Rating'] == df['Rating'].max()]
print(highest_rated_decorator)
cost_effective_decorator = df[df['Decoration Price'] == df['Decoration Price'].min()]
print(cost_effective_decorator)

    Unnamed: 0  Plate Cost  Decoration Price  Rating Caterer Name
15          15         320              5400     4.8            p
   Unnamed: 0  Plate Cost  Decoration Price  Rating Caterer Name
6           6         250              4200     3.4            g


In [9]:
# Caterer Analysis: Identify the caterer with the highest rating. Identify the most cost-effective caterer based on plate cost.
# 2. Caterer Analysis:
# Similar to decorator analysis, we identify the caterer with the highest rating and the most cost-effective caterer based on plate cost.
# “highest_rated_caterer” stores the caterer with the highest rating, and “cost_effective_caterer” stores the caterer with the lowest plate cost.
highest_rated_caterer = df[df['Rating'] == df['Rating'].max()]
print(highest_rated_caterer)
cost_effective_caterer = df[df['Plate Cost'] == df['Plate Cost'].min()]
print(cost_effective_caterer)

    Unnamed: 0  Plate Cost  Decoration Price  Rating Caterer Name
15          15         320              5400     4.8            p
    Unnamed: 0  Plate Cost  Decoration Price  Rating Caterer Name
6            6         250              4200     3.4            g
12          12         250              5000     4.3            m


In [10]:
# Caterer and Decorator Recommendations: Provide recommendations for selecting the best caterer and decorator based on customer satisfaction (rating)
# and cost-effectiveness (plate cost or decoration price).
# 3. Caterer and Decorator Recommendations:
# We provide recommendations for selecting the best caterer and decorator.
# “decorator_recommendation” suggests the highest-rated decorator with their rating.
decorator_recommendation = f"The highest-rated decorator is '{highest_rated_decorator['Caterer Name'].values[0]}' with a rating of {highest_rated_decorator['Rating'].values[0]}."
print(decorator_recommendation)
# “caterer_recommendation” suggests the most cost-effective caterer with their plate cost.
caterer_recommendation = f"The most cost-effective caterer is '{cost_effective_caterer['Caterer Name'].values[0]}' with a plate cost of {cost_effective_caterer['Plate Cost'].values[0]}."
print(caterer_recommendation)

The highest-rated decorator is 'p' with a rating of 4.8.
The most cost-effective caterer is 'g' with a plate cost of 250.


In [11]:
# Print the analysis results and recommendations
print("Decorator Analysis:")
print("Decorator with Highest Rating:")
print(highest_rated_decorator)
print("\nMost Cost-Effective Decorator:")
print(cost_effective_decorator)
print("\nCaterer Analysis:")
print("Caterer with Highest Rating:")
print(highest_rated_caterer)
print("\nMost Cost-Effective Caterer:")
print(cost_effective_caterer)
print("\nCaterer and Decorator Recommendations:")
print(decorator_recommendation)
print(caterer_recommendation)

Decorator Analysis:
Decorator with Highest Rating:
    Unnamed: 0  Plate Cost  Decoration Price  Rating Caterer Name
15          15         320              5400     4.8            p

Most Cost-Effective Decorator:
   Unnamed: 0  Plate Cost  Decoration Price  Rating Caterer Name
6           6         250              4200     3.4            g

Caterer Analysis:
Caterer with Highest Rating:
    Unnamed: 0  Plate Cost  Decoration Price  Rating Caterer Name
15          15         320              5400     4.8            p

Most Cost-Effective Caterer:
    Unnamed: 0  Plate Cost  Decoration Price  Rating Caterer Name
6            6         250              4200     3.4            g
12          12         250              5000     4.3            m

Caterer and Decorator Recommendations:
The highest-rated decorator is 'p' with a rating of 4.8.
The most cost-effective caterer is 'g' with a plate cost of 250.
